export type FaqItem = { question: string; answerHtml: string }
export type TemplateDownload = { label: string; href: string }
export type TemplateSection = { title: string; downloads: TemplateDownload[] }

export const FAQ_ITEMS: FaqItem[] = [
  { question: "How do I place an order?", answerHtml: "To place an order with us, follow these steps: <p><b>STEP 1.</b> Fill out the online <a href=\"/quote\">ORDER FORM</a> and complete all necessary fields with your project details.</p><p><b>STEP 2.</b> We email you a customized invoice with the final cost of the project. After checking that all information is accurate, pay the invoice.</p><p><b>STEP 3.</b> After the invoice has been paid, your job officially begins and is put into the production queue. Turnaround times start now.</p><p><b>STEP 4.</b> When your project has been completed, we will email you a status update letting you know. If shipping is required, you will be emailed a final invoice for shipping charges. Once paid, your order is sent.</p>" },
  { question: "What is your turnaround time?", answerHtml: "Although each project is different, we work hard to meet the deadlines of our clients and offer a quick turnaround time for many of our projects. Turnaround times begin the moment the order is officially paid for &amp; the digital proof is approved (see above). <p><b>PACKAGING:</b> Due to the many custom options we offer for packaging, there is a lead-in time to allow for shipping of the project&#8217;s stock. Therefore, most packaging jobs have a turnaround time of 15-25 business days.</p><p><i><b>NOTICE:</b> Turnaround times <b>DO NOT</b> include shipping. If you have a specific deadline that you need met that is outside of our current estimated turnaround times, please contact us to discuss RUSH pricing. For orders of 1000+ units, turnaround times are variable.</i></p>" },
  { question: "What are the artwork requirements?", answerHtml: "All artwork should be submitted using one of our pre-approved templates located on the <a href=\"/resources#templates\">TEMPLATES</a> page.Any font adjustments, sizing, placement, color choices, and layout are the responsibility of the customer to determine before placing an order.If a template does not exist for your project, or it is a custom sizing, please contact us first to discuss logistics and creation of a new custom template. <p><b>SUBMITTING ART:</b><span class=\"color\">ADOBE SUITE (PSD, EPS, AI)</span> &#8211; Artwork should be saved as a 300-600 DPI Photoshop or Illustrator file, with your art on separate layers for each color in the design, and clearly marked labels for ink colors. All fonts should be converted to shapes or included by email. We prefer vector art whenever possible.</p><p><span class=\"color\">ADOBE PDF (PDF)</span> &#8211; Artwork should be saved as a 300-600 DPI PDF file with layers &amp; editing still intact, OR as individual PDF files for each layer, with all template guides and labels turned off. All fonts should be converted to shapes or included by email.</p><p>JPEG, JPG, GIF, TIFF, PNG, or any other rasterized files that contain flattened layers are subject to a Design Fee (outlined below).</p><p><i>NOTICE: Any artwork which does not use our templates, is of poor resolution, or contains layers flattened together is subject to a Design Fee of $50 per hour with a 1 hour minimum, regardless of design complexity. While we do our best to catch errors as early as possible, we are not responsible for mistakes caused by misspellings and other design flaws in submitted artwork.</i></p>" },
  { question: "Can I supply my own lacquer, stampers, center labels, or packaging?", answerHtml: "<b>Lacquers:</b> Yes, you can provide your own lacquer. Please have it shipped to our headquarters.<br><br><b>Stamper:</b> You must co-ordinate with us to ensure the coining is correct for our record press.<br><br><b>Center Labels:</b> We prefer you co-ordinate with us to ensure proper compatibility to our machine.<br><br><b>Packaging:</b> Yes, we accept customer provided stock. However, please be aware that if this stock is shipped directly to NORP there is the possibility of misprints and/or damage, causing a quantity below what you have ordered. Therefore, we require customers to provide an extra 10% of units over the quantity needed. Customers who wish to supply their own stock must inquire with us first, including details about their desired product." },
  { question: "Will you help design my art?", answerHtml: "Absolutely! We have several professional in-house designers available. Please contact us for more details." },
  { question: "How do I make payments?", answerHtml: "Every project is paid via digital invoice. When we email you the project invoice, navigate to the payment gateway link inside the invoice. Choose your payment type and follow the instructions provided by each payment type.\n<p><i><b>NOTICE:</b> For customers who have arranged special payment terms, invoices must be paid in full within 10 business days of completion. Unpaid orders will incur a one-time late fee of $50 as well as 1% interest per week until paid in full.</i></p>" },
  { question: "What types of payment do you accept?", answerHtml: "We accept a multitude of payment types, each with their own benefits and requirements. Selection of payment type is made through our order tracking/payment system, which the email invoice will automatically direct you to. <p><b>CREDIT / DEBIT CARDS:</b> All major Credit and Debit cards can be accepted through use of Quickbooks, even if customer doesn&#8217;t have an account. <i>Notice: There is a 3.5% up-charge on all Credit / Debut card payments.</i></p><p><b>PAYPAL:</b> The quickest and easiest option for payment, Paypal allows instant transfer of funds from your online balance. <i>Notice: There is a 3.5% + $0.50 up-charge on all Paypal payments.</i></p><p><b>CHECK:</b> Checks should be made out to New Orleans Record Press, and mailed to 1336 Montegut Street New Orleans, LA 70117.<br><i>Notice: Checks must be received or sent via registered mail with tracking number provided in order for payment to be considered &#8220;paid.&#8221; Any returned checks due to insufficient funds will be billed an additional $35.</i></p><p><b>MONEY ORDER:</b> Money orders should be made out to New Orleans Record Press, and mailed to 1336 Montegut Street New Orleans, LA 70117.<br><i>Notice: All money orders must be received or sent via registered mail with tracking number provided in order for payment to be considered &#8220;paid.&#8221;</i></p><p><b>CASH:</b> Paying by cash is the absolute most reliable option, but requires payment to be delivered in person to New Orleans Record Press, 1336 Montegut Street New Orleans, LA 70117 during our normal business hours.<br><i>Notice: Cash is a local-only option.</i></p>" },
  { question: "How will I receive my finished items?", answerHtml: "Shipping damage is unfortunately commonplace in this business and here at New Orleans Record Press our standard shipping packaging includes double boxing and we also offer safe and affordable crating options to ensure your records will not be damaged. <p><b>LOCAL PICKUP:</b> For all local customers, businesses, and organizations, we encourage you to pick up your items directly from us during our normal business hours of 10AM &#8211; 6PM, Monday &#8211; Friday at 1336 Montegut Street New Orleans, LA.</p><p><b>SHIPPING:</b> We use USPS, UPS, FedEx for small deliveries and R&amp;L Carriers for freight. After orders have been completed, you will receive an email requiring final shipping payment. After they have left our shop, we&#8217;ll send an email with tracking number and confirmation of shipment, at which point your order will be marked SHIPPED.</p><p><i>NOTICE: Despite our best efforts, we are not responsible for delays, damages, or any other variances once the packages leave our hands. For damaged packages, please contact the shipping company to file a claim with their respective department.</i></p>" },
  { question: "What are your cancellation policies?", answerHtml: "<b>PRE-PRODUCTION:</b> Orders which are cancelled at any point before the artwork proof has been approved and/or the initiation of the lacquer cutting are entitled to a full refund minus a $50 cancellation fee as well as any fees incurred for design/audio work. <p><b>IN-PRODUCTION, BUT PRE-PRESSING:</b> Cancellation of any order which has already been marked as being IN PRODUCTION, are entitled to a refund of the project total minus the cost of any ordered stock, as well as any fees incurred for design/audio work.</p><p><b>POST-PRESSING:</b> No cancellations will be accepted once pressing, printing, or any manipulation of the product has been initiated.</p>" },
  { question: "What are your refund / replacement policies?", answerHtml: "Mistakes are possible in the manufacturing industry and we do our best to maximize quality and prevent errors in production. Everything we do is quality checked at multiple stages of production to guarantee consistent results.We do not refund misprints or mistakes caused by customer error. However, in the case of a major mistake, please contact us within 5 business days of arrival to discuss a solution." },
  { question: "Are there any scheduled closings or times your hours change?", answerHtml: "We work tirelessly to meet deadlines and assure a quick turnaround time, however, sometimes we need a break! We close for these holidays, and they are not included in our turnaround time estimates: <p>&#8211; Mardi Gras Day + Ash Wednesday</p><p>&#8211; Valentine\u2019s Day</p><p>&#8211; February 21st</p><p>&#8211; June 21st</p><p>&#8211; Halloween</p><p>&#8211; Thanksgiving + the day after</p><p>&#8211; Christmas Eve + Christmas Day + the day after</p><p>&#8211; New Year&#8217;s Eve + New Year\u2019s Day</p>" },
  { question: "What are your terms and conditions?", answerHtml: "Our terms and conditions are a legally binding agreement required for all projects.The full text can be found on our <a title=\"Terms and Conditions\" href=\"https://www.neworleansrecordpress.com/terms-and-conditions/\">Terms and Conditions</a> page." },
]

export const TEMPLATE_INTRO = {
  artworkSpecs: "All artwork should be submitted using one of our pre-approved templates located below. Any font adjustments, sizing, placement, color choices, and layout are the responsibility of the customer to determine before placing an order. There is a $50 Re-Proofing fee. Please triple check and make sure all typos, spelling and design choices are corrected before you send us files and we prep your files for printing. If a template does not exist for your project, or it is a custom sizing, please contact us first to discuss logistics and creation of a new custom template.",
  submittingArt: "ADOBE SUITE (PSD, EPS, AI) \u2013 Artwork should be saved as a 300-600 DPI UNFLATTENED Photoshop or Illustrator file, with your art on a separate layer from the template. All fonts should be converted to shapes or included by email. ADOBE PDF (PDF) \u2013 Artwork should be saved as a 300-600 DPI PDF file with layers & editing still intact, or with all template guides and labels turned off. All fonts should be converted to shapes or included by email. JPEG, JPG, GIF, TIFF, PNG, or any other rasterized files that contain flattened layers are not accepted. NOTICE: Any artwork which does not use our templates, is of poor resolution, or contains layers flattened together is subject to a Design Fee of $50 per hour with a 1 hour minimum, regardless of design complexity. While we do our best to catch errors as early as possible, we are not responsible for mistakes caused by misspellings and other design flaws in submitted artwork.",
}

export const TEMPLATE_SECTIONS: TemplateSection[] = [
  { title: "Templates \u2013 12\" Records", downloads: [
    { label: "CENTER LABEL : 4\u2033 Circle for 12\u2033 Records (Standard Bulk \u2013 Greater than 500 units)", href: "https://www.neworleansrecordpress.com/resources/NORP-centerlabel-BULK.pdf" },
    { label: "CENTER LABEL : 4\u2033 Circle for 12\u2033 Records (Low Run \u2013 500 units or less)", href: "https://www.neworleansrecordpress.com/resources/NORP-centerlabel.pdf" },
    { label: "JACKET : 12\u2033 Single Pocket Euro", href: "https://www.neworleansrecordpress.com/resources/NORP-jacket-singlepocket-euro.pdf" },
    { label: "JACKET : 12\u2033 Single Pocket (Low Run \u2013 500 units or less)", href: "https://www.neworleansrecordpress.com/resources/NORP-jacket-singlepocket-lowrun.pdf" },
    { label: "JACKET : 12\u2033 Single Pocket (Standard Bulk \u2013 Greater than 500 units)", href: "https://www.neworleansrecordpress.com/resources/NORP-jacket-singlepocket-standard.pdf" },
    { label: "JACKET : 12\u2033 Single Pocket (Wide Spine)", href: "https://www.neworleansrecordpress.com/resources/NORP-jacket-singlepocket-widespine.pdf" },
    { label: "JACKET : 12\u2033 Gatefold", href: "https://www.neworleansrecordpress.com/resources/NORP-jacket-gatefold.pdf" },
    { label: "JACKET : 12\u2033 Screen-Printed", href: "https://www.neworleansrecordpress.com/resources/NORP-jacket-singlepocket-standard.pdf" },
    { label: "INNER SLEEVE : Printed for 12\u2033 Records", href: "https://www.neworleansrecordpress.com/resources/NORP-printedinnersleeve.pdf" },
    { label: "INSERT : 12\u2033 x 12\u2033", href: "https://www.neworleansrecordpress.com/resources/NORP-insert-12x12.pdf" },
    { label: "INSERT : 24\u2033 x 12\u2033", href: "https://www.neworleansrecordpress.com/resources/NORP-insert-24x12.pdf" },
  ] },
  { title: "Templates \u2013 7\" Records", downloads: [
    { label: "CENTER LABEL : 7\u2033 Records (Small Hole)", href: "https://www.neworleansrecordpress.com/resources/NORP-seveninch-centerlabels-smallhole.pdf" },
    { label: "CENTER LABEL : 7\u2033 Records (Large Hole)", href: "https://www.neworleansrecordpress.com/resources/NORP-seveninch-centerlabels-largehole.pdf" },
    { label: "JACKET : 7\u2033 Glue Pocket", href: "https://www.neworleansrecordpress.com/resources/NORP-seveninch-gluepocket.pdf" },
    { label: "JACKET : 7\u2033 Glue Pocket with Die Cut Holes", href: "https://www.neworleansrecordpress.com/resources/NORP-seveninch-gluepocket-diecut.pdf" },
    { label: "JACKET : 7\u2033 Glue Pocket with Front Hole", href: "https://www.neworleansrecordpress.com/resources/NORP-seveninch-gluepocket-fronthole.pdf" },
  ] },
  { title: "Templates \u2013 Extras", downloads: [
    { label: "MARKETING STICKER : 2.5\u2033 x 3\u2033 Rectangle", href: "https://www.neworleansrecordpress.com/resources/NORP-marketingsticker-rectangle.pdf" },
    { label: "MARKETING STICKER : 2\u2033 Circle", href: "https://www.neworleansrecordpress.com/resources/NORP-marketingsticker-circle.pdf" },
    { label: "Download Cards", href: "https://www.neworleansrecordpress.com/resources/NORP-downloadcards-isong.pdf" },
  ] },
]
